services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata_volume:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_web
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8085:80"
    depends_on:
      - db

  # SeaweedFS
  master:
    image: chrislusf/seaweedfs
    container_name: seaweedfs_master
    ports:
      - "9333:9333"
    command: "master"

  volume:
    image: chrislusf/seaweedfs
    container_name: seaweedfs_volume
    ports:
      - "8081:8080"
    command: "volume -mserver=master:9333 -port=8080"
    depends_on:
      - master

  filer:
    image: chrislusf/seaweedfs
    container_name: seaweedfs_filer
    ports:
      - "8888:8888"
      - "8333:8333"
    command: 'filer -master="master:9333" -s3'
    depends_on:
      - master
      - volume

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_api
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - filer

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:3001/api/v1
    container_name: frontend_web
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - backend

volumes:
  pgdata_volume:

